covidhelp/covidhelp/urls.py
from django.contrib import admin
from django.urls import path , include
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView
from webapp.views import HomeView, \
    CovidHelpListView, CovidHelpCreateView, CovidHelpDetailsView, CovidHelpUpdateView, \
    AvailableDetailsView, AvailableCityListView, AvailableListView, AvailableCreateView, AvailableUpdateView, \
    LinkCreateView, LinkUpdateView, ContributorsView, SearchResultsView, TermsView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/',include('allauth.urls')),

    path('elangar/', include('food.urls')),

    path('logout',LogoutView.as_view(), name="logout"),

    path('', HomeView, name="home"),
    path('patients/', CovidHelpListView.as_view(), name="patient_lists"),
    path('patients/<pk>/', CovidHelpDetailsView.as_view(), name="covidhelp_details"),
    path('patients/add', CovidHelpCreateView.as_view(), name="add_patient"),
    path('patients/add/<int:pk>', CovidHelpUpdateView.as_view(), name="update_patient"),

    path('available/', AvailableListView.as_view(), name="available_lists"),
    path('available/<pk>/', AvailableDetailsView.as_view(), name="available_details"),
    path('available/add',AvailableCreateView.as_view(), name="add_available"),
    path('available/add/<int:pk>/', AvailableUpdateView.as_view(), name="update_available"),

    path('link/add' , LinkCreateView.as_view(), name="add_link"),
    path('link/<int:pk>/edit' , LinkUpdateView.as_view(), name="update_link"),

    path('contributors/', ContributorsView, name="contributors"),

    path('city/', SearchResultsView.as_view(), name="search_results"),
    path('city/<location>', AvailableCityListView.as_view(), name="available_city_lists"),

    path('terms-and-conditions',TermsView, name="terms-and-conditions"),



]

covidhelp/food/urls.py
from django.urls import path
from food.views import FoodIndex, VolunteerCreateView, CustomerCreateView, DonorCreateView

urlpatterns = [
    path('', FoodIndex, name="food_index"),
    path('add-customer' , CustomerCreateView.as_view(), name="add_customer"),
    path('add-volunteer' , VolunteerCreateView.as_view(), name="add_volunteer"),
    path('add-donor' , DonorCreateView.as_view(), name="add_donor"),
]

covidhelp/webapp/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

BLOODGROUP_CHOICES = [
    ('AB-','AB-'),
    ('AB','AB'),
    ('AB+','AB+'),
    ('A-','A-'),
    ('A','A'),
    ('A+','A+'),
    ('B-','B-'),
    ('B','B'),
    ('B+','B+'),
    ('O-','O-'),
    ('O','O'),
    ('O+','O+'),
    ('ANY','ANY'),
]


STATUS_CHOICES = [
    ('O', 'Open'),
    ('C', 'Closed'),
]

VERIFIED_CHOICES = [
    ('U', 'Unverified'),
    ('V', 'Verified'),
    ('F', 'Fake')
]

class Requirements(models.Model):
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=200,null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']

class CovidHelp(models.Model):
    patient_name = models.CharField(max_length=100)
    patient_contact_no = models.CharField(max_length=15)
    patient_email=models.EmailField(blank=True)
    patient_age = models.CharField(max_length=3)
    patient_blood_group = models.CharField(max_length=3, choices = BLOODGROUP_CHOICES, default="ANY")
    patient_sp02_level = models.CharField(max_length=2)
    patient_requirements = models.ForeignKey(Requirements, on_delete=models.CASCADE, null=True, blank=True)


    alternate_contact = models.CharField(blank=True, max_length=100)
    alternate_contact_no = models.CharField(blank=True, max_length=15)

    location_city = models.CharField(max_length=30, help_text="The city where the patient needs help")
    location_hospital=models.CharField(blank=True, max_length=100, help_text="If the patient is aleady in a hospital")

    status = models.CharField(max_length=1, choices = STATUS_CHOICES, default="O")
    date = models.DateTimeField(auto_now=True)

    additional_text = models.TextField(blank=True, help_text="Any additional details you may want to give")
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        return self.patient_name


    class Meta:
        ordering = ["patient_requirements","-date"]

class Available(models.Model):
    type = models.ForeignKey(Requirements, on_delete=models.CASCADE, null=True, blank=True)
    contact_name = models.CharField(max_length=100)
    contact_number = models.CharField(max_length=15)
    location = models.CharField(max_length=30)
    verified = models.CharField(max_length=1, choices=VERIFIED_CHOICES, default='U')
    last_verified = models.DateTimeField(auto_now=True)
    additional_text=models.TextField(blank=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.contact_name

    class Meta:
        ordering =["type","-last_verified"]


class Category(models.Model):
    name=models.CharField(max_length=20)

    def __str__(self):
        return self.name

    class Meta:
        ordering=['name']


class Link(models.Model):
    name = models.CharField(max_length=100)
    url = models.URLField(unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        ordering=['category','name']

covidhelp/templates/base.html
<!DOCTYPE html>
{% load socialaccount %}
<html>
<head>
  <title>CovidSAVE: {% block content_heading %}{% endblock content_heading %}</title>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css">
  <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css">
  <style>


  #tabs-with-content .tabs:not(:last-child) {
    margin-bottom: 0;
  }

  #tabs-with-content .available-tab-content {
    padding: 1rem;
    display: none;
  }

  #tabs-with-content .available-tab-content.is-active {
    display: block;
  }

  #help-tabs-with-content .tabs:not(:last-child) {
    margin-bottom: 0;
  }

  #help-tabs-with-content .available-tab-content {
    padding: 1rem;
    display: none;
  }

  #help-tabs-with-content .available-tab-content.is-active {
    display: block;
  }


  </style>

</head>
<body>
  <code> <b>DISCLAIMER</b> : The material and information contained on this website is for general information purposes only and is not professional advice. By using this website you are agreeing with the <b><a href="{% url 'terms-and-conditions' %}">Terms and Conditions</a></b>. </code>

  <nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href="/">
        <div class="title">CovidSAVE</div>
      </a>
      <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-start">
        <a class="navbar-item" href="{% url 'available_lists' %}">
          Available
        </a>

        <a class="navbar-item" href="{% url 'patient_lists'%}">
          Help needed
        </a>
        <a class="navbar-item" href="{% url 'contributors' %}">
          Contributors
        </a>

      </div>
    </div>
      <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">
          {% if user.is_authenticated %}
            Logged in as &nbsp; <strong>{{ user|capfirst }}</strong> [ <a href="{% url 'logout' %}">Logout</a> ]
          {% else %}
            <a href="{% url 'account_signup' %}" class="button is-light">
              <strong>Sign up</strong>
            </a>
            <a href="{% url 'account_login' %}" class="button is-primary">
              Log in
            </a>
          {% endif %}
          </div>
        </div>
      </div>
    </div>
  </nav>
  <!-- search box -->
  <div class="box">
        <form class="field has-addon" action={% url 'search_results' %} method="GET" value="{{request.GET.q}}">
               <input class="" type="text" name="q" value ="{{request.GET.q}}" placeholder="City Search..." />
               <input class="button is-info is-small" type="submit" value="Search">
        </form>
  </div>





  {% block content_menu %} {% endblock content_menu %}
  {% block content_body %} {% endblock content_body %}

  <!-- Footer section -->
  <footer class="footer">
  <div class="content has-text-centered">
    <p>
      Developed by <a href="https://www.twitter.com/vibhurishi" target="new">@vibhurishi</a>. A small effort for the massive fight against the Covid-19 pandemic.
    </p>
  </div>
  </footer>

  <script type="text/javascript">
    let tabsWithContent = (function () {
    let tabs = document.querySelectorAll('.avail-tabs li');
    let tabsContent = document.querySelectorAll('.available-tab-content');

    let deactvateAllTabs = function () {
      tabs.forEach(function (tab) {
        tab.classList.remove('is-active');
      });
    };

    let hideTabsContent = function () {
      tabsContent.forEach(function (tabContent) {
        tabContent.classList.remove('is-active');
      });
    };

    let activateTabsContent = function (tab) {
      tabsContent[getIndex(tab)].classList.add('is-active');
    };

    let getIndex = function (el) {
      return [...el.parentElement.children].indexOf(el);
    };

    tabs.forEach(function (tab) {
      tab.addEventListener('click', function () {
        deactvateAllTabs();
        hideTabsContent();
        tab.classList.add('is-active');
        activateTabsContent(tab);
      });
    })

    tabs[0].click();
  })();

  let tabsWithContentHelp = (function () {
  let tabs = document.querySelectorAll('.help-tabs li');
  let tabsContent = document.querySelectorAll('.help-tab-content');

  let deactvateAllTabs = function () {
    tabs.forEach(function (tab) {
      tab.classList.remove('is-active');
    });
  };

  let hideTabsContent = function () {
    tabsContent.forEach(function (tabContent) {
      tabContent.classList.remove('is-active');
    });
  };

  let activateTabsContent = function (tab) {
    tabsContent[getIndex(tab)].classList.add('is-active');
  };

  let getIndex = function (el) {
    return [...el.parentElement.children].indexOf(el);
  };

  tabs.forEach(function (tab) {
    tab.addEventListener('click', function () {
      deactvateAllTabs();
      hideTabsContent();
      tab.classList.add('is-active');
      activateTabsContent(tab);
    });
  })

  tabs[0].click();
  })();
  </script>

</body>

</html>

covidhelp/templates/index.html
{% extends "base.html" %}

{% block content_heading %} Saving everyone from Covid {% endblock content_heading%}

{%block content_menu%}
<div class="box is-hidden-desktop">
  Quick jump:

  <a href="#links">
    Useful Links
  </a>
  /
  <a href="#available">
    Available
  </a>
  /
  <a href="#helpneeded">
    Help Needed
  </a>

</div>
{%endblock content_menu %}


{% block content_body %}

<p><code>Note: Click on name for more details. Click on city for list in city.</code></p>
<section class="section">
  <div class = "columns">

    <div class="column is-one-third"">  <!-- Links start -->
      {% regroup link_list by category as links %}
      <!-- header -->
      <article class="message">
        <div class="message-header">
          <p><a id="links" class="subtitle"> Useful Links </a> <span class="tag">{{link_list|length}}</span></p>
          <a href="{% url "add_link" %}" class="button is-small is-rounded">+ Add</a>
          </div>
      </article>
      <!-- content -->
      <div class="content">

        {% for link in links %}
        <p class="panel-block">
          <b>{{link.grouper}}</b>
          </p>
          <ul>
            {% for item in link.list %}
              <li>
                <a href="{{item.url}}" target="new">

                {{item.name}}
                </a>
                <small> <i>added by {{item.created_by}}</i></small>
                {% if user.is_authenticated %}
                  {% ifequal request.user item.created_by %}
                    <span class="is-size-7">
                    <small>[<a href="{% url "update_link" item.pk %}">Edit</a>]</small>
                    </span>
                  {% endifequal %}
                {% endif %}
              </li>
            {% endfor %}
            </ul>
        {% endfor %}

      </div>
    </div>                <!-- Links end -->

    <div class="column is-one-third">  <!-- Available start -->
      <article class="message">
          <div class="message-header ">
            <p><a id="available" class="subtitle" href="{% url 'available_lists' %}">Availability</a> <span class="tag"> {{available_count}} </span></p>
            <a href="{% url "add_available" %}" class="button is-small is-rounded">+ Add</a>
          </div>
      </article>
      <!-- content -->
      {% regroup available_list by type as type_list %}
            You are searching for :
            {% for types in type_list %}
            <a href="#{{types.grouper}}">{{types.grouper}}</a> <span class=""><sup>({{types.list|length}})</sup></span>
            /
            {% endfor %}
            <hr>
            <div>
            {% for types in type_list %}
                <p class="panel-heading">
                  <b id="{{types.grouper}}">{{types.grouper}} </b>
                </p>
                {% if types.grouper.description %}
                <p class="panel-block has-background-warning-light is-size-7 ">
                  {{types.grouper.description|urlize}}
                </p>
                {% endif %}

                {% for item in types.list %}
                <div>
                  {% if item.verified == "V" %}
                    <div class="tag is-success">
                    {% elif item.verified == "U" %}
                    <div class="tag is-warning">
                    {% else %}
                    <div class="tag is-danger">
                    {% endif %}
                    {{item.get_verified_display}}
                    </div>
                    <a href="{% url "available_details" item.pk %}">{{item}}</a> [{{item.contact_number}}] in <a href="{% url "available_city_lists" item.location %}">{{item.location}}</a>
                    {% if item.additional_text %}
                      <br><small class="has-text-grey">{{item.additional_text|truncatechars:30}}<a href="{% url "available_details" item.pk %}"> ...more. </a></small>
                    {% endif %}


                    <small class="is-pulled-right">
                      Last update : {{item.last_verified|timesince}} ago by <i>{{item.created_by}}</i>
                      {% if user.is_authenticated %}
                        {% ifequal request.user item.created_by %}
                          [<a href="{% url "update_available" item.pk %} ">Edit</a>]
                        {% endifequal %}
                      {% endif %}
                    </small>
                </div>
                {% endfor %}

                <hr>

            {% endfor %}
            </div>

    </div>                <!-- Available end -->

    <div class="column is-one-third">  <!-- Required start -->
      <article class="message">
        <div class="message-header">
          <p> <a id="helpneeded" class="subtitle" href="{% url 'patient_lists'%}">Help needed</a> <span class="tag">{{help_count}}</span></p>
          <a href="{% url "add_patient" %}" class="button is-small is-rounded">+ Add</a>
        </div>
      </article>
      <!-- content -->
      {% regroup help_required_list by patient_requirements as help_list %}

        {% for patient_requirements in help_list %}
        <p class="panel-heading">
          <b>{{patient_requirements.grouper}} Required</b>
          </p>
          <hr>
            {% for item in patient_requirements.list %}
              <a href="{% url "covidhelp_details" item.pk %}">{{item.patient_name}}</a> [{{item.patient_contact_no}}] in {{item.location_city}}
              {% if user.is_authenticated %}
                {% ifequal request.user item.created_by %}
                  <span class="is-size-7">
                  <small>[<a href="{% url "update_patient" item.pk %} ">Edit</a>]</small>
                  </span>
                {% endifequal %}
              {% endif %}
              <br>
              <small>SPO2 : <strong>{{item.patient_sp02_level}}</strong> / BG : <strong>{{item.patient_blood_group}}</strong> / Age : <strong>{{item.patient_age}}</strong></small><br>
              <small class="is-pulled-right">Updated {{item.date|timesince}} ago by <i>{{item.created_by}}</i>.
                Status is
                {% if item.type == "C" %}
                  <div class="tag is-success">
                  {% else %}
                  <div class="tag is-warning">
                  {% endif %}
                  {{item.get_status_display}}
                  </div>
                </small>
              <hr>
            {% endfor %}
        {% endfor %}

    </div>                <!-- Required end -->



  </div> <!-- columns -->

</section>
{% endblock content_body %}